### PR TITLE
Fail only single request on too large frame

### LINKED ISSUE #99: Fail only a single request on TooLongFrameException
Currently the `TooLongFrameException` results in disconnect. If connection pooling is enabled it results in failure of all the requests that are currently processed by the connection.

When connection pooling is enabled, only a culprit request must be failed with `TooLongFrameException`. To achieve that, the oversized response must be skipped, sequence id must be decoded during skip, and only the request that caused this failure must be failed.

### PR DESCRIPTION
**Pull request by arhimondr**
Resolves #99

### CODE REVIEW

**Comment by arhimondr** [comment]
First 4 commits 

```
- Check if pooled connection is still open
- Don't log connection close exceptions in Drift server
- Close connection in case of unexpected exception in Drift server
- Add delay before retrying same address 
```

Are from previous 2 PR's: #95, #101

Only 

```
- Fix FB_COMPACT message type decoding
- Don't fail all requests on the channel in case of too long frame
```

are actually part of this PR

File: drift-api/src/main/java/io/airlift/drift/TApplicationException.java [hunk 1]
```diff
@@ -44,7 +44,8 @@
         PROTOCOL_ERROR(7),
         INVALID_TRANSFORM(8),
         INVALID_PROTOCOL(9),
-        UNSUPPORTED_CLIENT_TYPE(10);
+        UNSUPPORTED_CLIENT_TYPE(10),
+        TOO_LARGE_REQUEST(11);
```
Comment (electrum) [inline drift-api/src/main/java/io/airlift/drift/TApplicationException.java]: We shouldn't add an additional code here as this won't be compatible with other implementations. [Apache Thrift](https://github.com/apache/thrift/blob/master/lib/cpp/src/thrift/TApplicationException.h) stops at 10, but [Facebook Thrift](https://github.com/facebook/fbthrift/blob/master/thrift/lib/cpp/TApplicationException.h) adds 11-13. Probably best to use `PROTOCOL_ERROR`. @dain thoughts?

Comment (arhimondr) [reply drift-api/src/main/java/io/airlift/drift/TApplicationException.java]: I didn't know this enum is the part of the Thrift standard. I don't think it makes sense to break compatibility for this error. Let me use `PROTOCOL_ERROR` instead.

Comment (dain) [reply drift-api/src/main/java/io/airlift/drift/TApplicationException.java]: I agree adding new codes is dangerous for future comparability.  Also no other client will support them.

File: drift-integration-tests/src/test/java/io/airlift/drift/integration/guice/ThrowingServiceHandler.java [hunk 2]
```diff
@@ -15,11 +15,20 @@
...
+
+import javax.annotation.concurrent.GuardedBy;
+
+import static com.google.common.util.concurrent.Futures.immediateFuture;
 import static java.lang.Math.toIntExact;
 
 public class ThrowingServiceHandler
         implements ThrowingService
 {
+    @GuardedBy("this")
```
Comment (electrum) [inline drift-integration-tests/src/test/java/io/airlift/drift/integration/guice/ThrowingServiceHandler.java]: Given the usage pattern, we could make this final and initialize the future here. Alternatively, should we clear the future field in `release()` (so the service could be called multiple times)?

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/client/ThriftClientHandler.java [hunk 3]
```diff
@@ -209,13 +211,16 @@ public void channelInactive(ChannelHandlerContext context)
 
     private void onError(ChannelHandlerContext context, Throwable throwable, Optional<RequestHandler> currentRequest)
     {
+        if (throwable instanceof FrameTooLargeException) {
+            checkArgument(!currentRequest.isPresent(), "in case of FrameTooLargeException current request is not expected to be set");
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/client/ThriftClientHandler.java]: We can simplify this wording
```java
"current request should not be set for FrameTooLargeException"

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/FrameInfo.java [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+    @Override
+    public boolean equals(Object o)
+    {
+        if (this == o) {
+            return true;
+        }
+        if (o == null || getClass() != o.getClass()) {
+            return false;
+        }
+        FrameInfo frameInfo = (FrameInfo) o;
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/FrameInfo.java]: Nit: use the IntelliJ default of `that` for the variable name

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/FrameTooLargeException.java [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+        extends DecoderException
+{
+    private final Optional<FrameInfo> frameInfo;
+    private final long frameSizeInBytes;
+    private final int maxFrameSizeInBytes;
+
+    public FrameTooLargeException(Optional<FrameInfo> frameInfo, long frameSizeInBytes, int maxFrameSizeInBytes)
+    {
+        this.frameInfo = requireNonNull(frameInfo, "sequenceId is null");
+        checkArgument(frameSizeInBytes >= 0, "frameSizeInBytes must be greater than or equal to zero");
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/FrameTooLargeException.java]: Maybe simplify to "cannot be negative"

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/FrameTooLargeException.java [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+
+    public Optional<FrameInfo> getFrameInfo()
+    {
+        return frameInfo;
+    }
+
+    @Override
+    public String getMessage()
+    {
+        return format("Frame size exceeded. frameInfo: %s, frameSizeInBytes: %s, maxFrameSizeInBytes: %s", frameInfo, frameSizeInBytes, maxFrameSizeInBytes);
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/FrameTooLargeException.java]: How about formatting like this
```java
return format("Frame size %s exceeded max size %s: %s", succinctBytes(frameSizeInBytes), succinctBytes(maxFrameSizeInBytes), frameInfo);
```
The `toString()` for `FrameInfo` will include the class name, so we don't need to repeat it.

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/HeaderTransport.java [hunk 7]
```diff
@@ -197,6 +189,18 @@ public static ThriftFrame decodeFrame(ByteBuf buffer)
...
     }
 
+    private static boolean isOutOrOrderResponseSupported(short flags)
+    {
+        switch (flags) {
+            case FLAGS_NONE:
+                return false;
+            case FLAG_SUPPORT_OUT_OF_ORDER:
+                return true;
+            default:
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/HeaderTransport.java]: The throw can move outside the switch

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/HeaderTransport.java [hunk 8]
```diff
@@ -240,4 +244,38 @@ private static int readVariableLengthInt(ByteBuf messageHeader)
...
+            int sequenceId = buffer.readInt();
+            int headerSize = buffer.readShort() << 2;
+
+            if (buffer.readableBytes() < Byte.BYTES) {
+                return Optional.empty();
+            }
+            byte protocolId = buffer.getByte(buffer.readerIndex());
+            Protocol protocol = Protocol.getProtocolByHeaderTransportId(protocolId);
+
+            if (buffer.readableBytes() < headerSize) {
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/HeaderTransport.java]: I think this check needs to be above the `buffer.getByte()` for the protocol ID, since that is included in the header size (based on my reading of `decodeFrame()`)

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/SimpleFrameInfoDecoder.java [hunk 9]
```diff
@@ -0,0 +1,68 @@
...
+    {
+        TChannelBufferInputTransport transport = new TChannelBufferInputTransport(buffer.retainedDuplicate());
+        try {
+            TProtocol protocol = protocolType.createProtocol(transport);
+            TMessage message;
+            try {
+                message = protocol.readMessageBegin();
+            }
+            catch (TException | RuntimeException e) {
+                // not enough bytes in the input to decoded sequence id
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/SimpleFrameInfoDecoder.java]: Typo: decoded -> decode

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/HeaderTransport.java [hunk 10]
```diff
@@ -240,4 +244,38 @@ private static int readVariableLengthInt(ByteBuf messageHeader)
...
+                return Optional.empty();
+            }
+            buffer.skipBytes(headerSize);
+            SimpleFrameInfoDecoder simpleFrameInfoDecoder = new SimpleFrameInfoDecoder(HEADER, protocol, outOfOrderResponse);
+            return simpleFrameInfoDecoder.tryDecodeFrameInfo(buffer)
+                    // prefer sequence id from the frame header
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/HeaderTransport.java]: Why would they be different? Should we fail if they are?

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/ThriftFramedDecoder.java [hunk 11]
```diff
@@ -0,0 +1,118 @@
...
+            ByteBuf frame = buffer.retainedSlice(buffer.readerIndex(), toIntExact(frameSizeInBytes));
+            buffer.readerIndex(buffer.readerIndex() + toIntExact(frameSizeInBytes));
+            return frame;
+        }
+
+        buffer.readerIndex(initialReaderIndex);
+        return null;
+    }
+
+    private void discardingTooLongFrame(ByteBuf buffer)
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/ThriftFramedDecoder.java]: Name `discardTooLongFrame()` so that it's a verb

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/ThriftFramedDecoder.java [hunk 12]
```diff
@@ -0,0 +1,118 @@
...
+                bytesToDiscard = frameSizeInBytes;
+                discardingTooLongFrame(buffer);
+                return null;
+            }
+            buffer.readerIndex(initialReaderIndex);
+            return null;
+        }
+
+        if (buffer.readableBytes() >= frameSizeInBytes) {
+            // toIntExact must be save, as frameSizeInBytes <= maxFrameSize
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/ThriftFramedDecoder.java]: Type: save -> safe

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/ThriftFramedDecoder.java [hunk 13]
```diff
@@ -0,0 +1,118 @@
...
+            // this invocation doesn't move the readerIndex
+            Optional<FrameInfo> frameInfo = frameInfoDecoder.tryDecodeFrameInfo(buffer);
+            if (frameInfo.isPresent()) {
+                tooLongFrameInfo = frameInfo;
+                tooLongFrameSizeInBytes = frameSizeInBytes;
+                bytesToDiscard = frameSizeInBytes;
+                discardingTooLongFrame(buffer);
+                return null;
+            }
+            // basic frame info cannot be decoded, and the max frame size already exceeded
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/ThriftFramedDecoder.java]: These are two sentences, so make them
```java
// Basic frame info cannot be decoded and the max frame size is already exceeded.
// Instead of waiting forever, fail without providing the sequence ID.

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/ThriftUnframedDecoder.java [hunk 14]
```diff
@@ -51,13 +55,16 @@ protected final void decode(ChannelHandlerContext ctx, ByteBuf buffer, List<Obje
...
 
-            protocolReader.readMessageBegin();
+            TMessage message = protocolReader.readMessageBegin();
             TProtocolUtil.skip(protocolReader, TType.STRUCT);
             protocolReader.readMessageEnd();
 
             int frameLength = buffer.readerIndex() - frameOffset;
             if (frameLength > maxFrameSize) {
-                ctx.fireExceptionCaught(new TooLongFrameException("Response message exceeds max size " + maxFrameSize + ": " + frameLength + " - discarded"));
+                ctx.fireExceptionCaught(new FrameTooLargeException(
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/ThriftUnframedDecoder.java]: Maybe format as
```java
FrameInfo frameInfo = new FrameInfo(message.getName(), message.getType(), message.getSequenceId(), UNFRAMED, protocol, assumeClientsSupportOutOfOrderResponses);
ctx.fireExceptionCaught(new FrameTooLargeException(Optional.of(frameInfo), frameLength, maxFrameSize));

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/ThriftFramedDecoder.java [hunk 15]
```diff
@@ -0,0 +1,118 @@
...
+
+    private void discardingTooLongFrame(ByteBuf buffer)
+    {
+        // readableBytes returns int, toIntExact must be safe
+        int bytesToSkip = toIntExact(min(bytesToDiscard, buffer.readableBytes()));
+        buffer.skipBytes(bytesToSkip);
+        bytesToDiscard -= bytesToSkip;
+
+        if (bytesToDiscard == 0) {
+            FrameTooLargeException exception = new FrameTooLargeException(tooLongFrameInfo, tooLongFrameSizeInBytes, maxFrameSizeInBytes);
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/ThriftFramedDecoder.java]: Maybe shorten to `RuntimeException e = ...`

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/server/ThriftServerHandler.java [hunk 16]
```diff
@@ -100,9 +103,33 @@ public void channelRead(ChannelHandlerContext context, Object message)
...
+                            frameInfo.getProtocol(),
+                            frameInfo.getSequenceId(),
+                            frameInfo.isSupportOutOfOrderResponse(),
+                            PROTOCOL_ERROR,
+                            e.getMessage(),
+                            e));
+                }
+                catch (Throwable t) {
+                    context.close();
+                    log.error(t);
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/server/ThriftServerHandler.java]:
```java
log.error(t, "Failed to write frame info");

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/server/ThriftServerHandler.java [hunk 17]
```diff
@@ -100,9 +103,33 @@ public void channelRead(ChannelHandlerContext context, Object message)
...
+                }
+                return;
+            }
+        }
+
+        context.close();
```
Comment (electrum) [inline drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/server/ThriftServerHandler.java]: Add newline after this

File: drift-integration-tests/src/test/java/io/airlift/drift/integration/guice/ThrowingServiceHandler.java (hunk 2 above)
Comment (arhimondr) [reply drift-integration-tests/src/test/java/io/airlift/drift/integration/guice/ThrowingServiceHandler.java]: > Alternatively, should we clear the future field 

+1

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/HeaderTransport.java (hunk 10 above)
Comment (arhimondr) [reply drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/HeaderTransport.java]: No idea. You are right, let me add an assertion.

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/HeaderTransport.java [hunk 18]
```diff
@@ -240,4 +244,47 @@ private static int readVariableLengthInt(ByteBuf messageHeader)
...
+                return Optional.empty();
+            }
+            // skip magic
+            buffer.readShort();
+            short flags = buffer.readShort();
+            boolean outOfOrderResponse = isOutOrOrderResponseSupported(flags);
+            int headerSequenceId = buffer.readInt();
+            int headerSize = buffer.readShort() << 2;
+
+            if (buffer.readableBytes() < Byte.BYTES) {
```
[the remark this answers is not in the document]
Comment (arhimondr) [reply drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/HeaderTransport.java]: Yeah, this check is extra.

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/HeaderTransport.java [hunk 19]
```diff
@@ -240,4 +244,47 @@ private static int readVariableLengthInt(ByteBuf messageHeader)
...
+                return Optional.empty();
+            }
+
+            if (buffer.readableBytes() < headerSize) {
+                return Optional.empty();
+            }
+
+            byte protocolId = buffer.getByte(buffer.readerIndex());
+            Protocol protocol = Protocol.getProtocolByHeaderTransportId(protocolId);
```
[the remark this answers is not in the document]
Comment (arhimondr) [reply drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/HeaderTransport.java]: It can throw only if client/server tries to use unsupported protocol. In that case there's nothing else we can do, but close the connection anyway.

File: drift-transport-spi/src/main/java/io/airlift/drift/transport/client/MessageTooLargeException.java [hunk 20]
```diff
@@ -17,10 +17,10 @@
 
 import io.airlift.drift.protocol.TTransportException;
 
-public class FrameTooLargeException
+public class MessageTooLargeException
```
[the remark this answers is not in the document]
Comment (arhimondr) [reply drift-transport-spi/src/main/java/io/airlift/drift/transport/client/MessageTooLargeException.java]: Just to avoid name clash. `FrameTooLargeException` now extends the `DecoderException`, and indicates max frame size overflow in FrameDecoder. `MessageTooLargeException` is a `TTransportException`.

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/ThriftFramedDecoder.java [hunk 21]
```diff
@@ -0,0 +1,118 @@
...
+    @Override
+    protected void decode(ChannelHandlerContext context, ByteBuf buffer, List<Object> output)
+    {
+        Object result = decode(buffer);
+        if (result != null) {
+            output.add(result);
+        }
+    }
+
+    private Object decode(ByteBuf buffer)
```
[the remark this answers is not in the document]
Comment (arhimondr) [reply drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/ThriftFramedDecoder.java]: I thought about this as of a hot spot. But i agree that the cost of creating a one `Optional` object per request is negligible comparing to the cost of decoding and processing.

File: drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/FrameInfoDecoder.java [hunk 22]
```diff
@@ -0,0 +1,28 @@
...
+import io.netty.buffer.ByteBuf;
+
+import java.util.Optional;
+
+interface FrameInfoDecoder
+{
+    /**
+     * Attempts to decode basic frame info without moving the reader index
+     */
+    Optional<FrameInfo> tryDecodeFrameInfo(ByteBuf buffer);
```
[the remark this answers is not in the document]
Comment (arhimondr) [reply drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/codec/FrameInfoDecoder.java]: It also contains the information about the Frame encoding and about the underlying protocol (transport, protocol).

**Comment by arhimondr** [comment]
@dain updated
